version: '3'
services:
  eureka:
    image: localhost:5000/eureka-9003
#    image: swarm.inf.uniroma3.it:5000/eureka-9003
#    container_name: eureka
#    ports:
#    - "8761:8761"
    deploy:
      placement:
        constraints: [node.role == manager]
  brands-sales:
      image: localhost:5000/brands-sales-9003
#    image: swarm.inf.uniroma3.it:5000/brands-sales-9003
#    ports:
#    - "8080"
    depends_on:
    - "eureka"
    deploy:
      mode: replicated
      replicas: 1
  brands-famous:
     image: localhost:5000/brands-famous-9003
#    image: swarm.inf.uniroma3.it:5000/brands-famous-9003
#    ports:
#    - "8080"
    depends_on:
    - "eureka"
    deploy:
      mode: replicated
      replicas: 1
  brands:
    image: localhost:5000/brands-9003
#    image: swarm.inf.uniroma3.it:5000/brands-9003
#    ports:
#    - "8080"
    depends_on:
    - "eureka"
    deploy:
      mode: replicated
      replicas: 2
  zuul:
    image: localhost:5000/zuul-9003
#    image: swarm.inf.uniroma3.it:5000/zuul-9003
#    container_name: zuul
    depends_on:
    - "eureka"
    ports:
    - "9003:8080"
