#
# Vagrantfile per un singolo nodo (dev, developer)
# per la compilazione dei progetti,
# con Oracle Java, Gradle e Maven.
#

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # Configurazioni comuni.

    # Ubuntu Trusty (14.04 LTS) 64 bit VirtualBox.
    config.vm.box = "ubuntu/trusty64"

    # folder per i progetti (/home/vagrant/projects)
    config.vm.synced_folder "../../progetti/", "/home/vagrant/projects", :mount_options => ["dmode=777", "fmode=777"]

    # folder per le risorse condivise (/home/vagrant/shared/resources e /home/vagrant/shared/scripts)
    config.vm.synced_folder "../shared/", "/home/vagrant/shared", :mount_options => ["dmode=777", "fmode=777"]

    #
      # Configurazione del nodo "dev":

      config.vm.define "dev" do |node|
          node.vm.hostname = "dev"
          node.vm.network "private_network", ip: "10.11.1.51", virtualbox__intnet: true

          node.vm.provider "virtualbox" do |v|
               v.memory = 4096
               v.cpus = 2
          end
          # porta ssh
          node.vm.network "forwarded_port", guest: 22, host: 2222, id: 'ssh', host_ip: "localhost",auto_correct: true
          node.ssh.forward_agent = true

          # porte
          node.vm.network "forwarded_port", guest: 8080, host: 8088, id: 'S',  host_ip: "localhost", auto_correct: true
          node.vm.network "forwarded_port", guest: 8081, host: 8081, id: 'S1', host_ip: "localhost", auto_correct: true
          node.vm.network "forwarded_port", guest: 8082, host: 8082, id: 'S2', host_ip: "localhost", auto_correct: true

          # provisioning con bash
          node.vm.provision :shell, :inline => 'apt-get update'
          node.vm.provision :shell, path: "../shared/scripts/setup-java.sh"
          node.vm.provision :shell, path: "../shared/scripts/setup-gradle.sh"
          node.vm.provision :shell, path: "../shared/scripts/setup-maven.sh"

          node.vm.provision :shell,
              inline: "echo  'configurazione nodo developer completata'"

          # istruzioni per l'avvio
          node.vm.provision :shell, run:"always",
                inline: "echo 'Aprire tre terminali, posizionarsi nella cartella developer ed eseguire rispettivamente:' &&
                         echo '$ vagrant ssh dev \t\t $ sh shared/scripts/startup1.sh' &&
  		                   echo '$ vagrant ssh dev \t\t $ sh shared/scripts/startup2.sh' &&
  		                   echo '$ vagrant ssh dev \t\t $ sh shared/scripts/startup3.sh '"

      end

end
